### ISSUE TITLE
Arm Thrust causes the game to freeze with music still playing

### ISSUE THREAD

**Issue by Aliaxiner** [BluRosie/hg-engine#186] opened 2024-01-23 23:35 UTC
The move Arm Thrust causes the game to completely hang. I've first encountered this when using a Pancham and also encountering one in the wild. I'd imagine this would effect any other pokemon knowing this move.

**Comment by BluRosie** [comment] 2024-01-25 01:14
are you on melonDS, hardware, desmume?  what is pancham using it on?

**Comment by Aliaxiner** [comment] 2024-01-25 02:32
I've used it on Desmume, Drastic and TwilightMenu, it seems to be both wild Pancham and any I catch. As soon as the move is used the game hangs completely with the music still playing.

**Comment by BluRosie** [comment] 2024-02-17 01:42
this is probably fixed now after i merge in the pending PR
are you able to test it soon?  i wasn't able to reproduce under any circumstances on my end

**Comment by BluRosie** [comment] 2024-03-10 04:49
closing due to inactivity--feel free to leave a comment up and i will reopen it.  i believe i have fixed it due to merging that PR, but i can not know for sure without your systems--tested on melonDS and twlmenu on my end

**Closed by BluRosie** 2024-03-10 04:49 UTC
Labels: bug, moves, non-reproducible
